### ISSUE TITLE
Error trying to build on Windows 11

### ISSUE THREAD

**Issue by leomarques** [eddex/aseprite-windows-docker-build#10] opened 2023-10-23 09:19 UTC
I just get this error after a few minutes building aseprite
![Sem título](https://github.com/eddex/aseprite-windows-docker-build/assets/1104925/fbe021d2-82a9-4585-bc57-c22339dce38a)
any help?

**Comment by eddex** [comment] 2023-10-23 18:09
Hi @leomarques 

Thanks for reporting this issue. I tried it on my machine (Windows 10) and can reproduce it.

```powershell
aseprite-windows-docker-build git:(master) > .\start.bat
Building Aseprite using Docker
[+] Building 229.0s (6/8)
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                   0.1s
 => => transferring dockerfile: 117B                                                                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                      0.1s
 => => transferring context: 2B                                                                                                                                                                                                                        0.0s
 => [internal] load metadata for docker.io/abrarov/msvc-2019:latest                                                                                                                                                                                    2.3s
 => [auth] abrarov/msvc-2019:pull token for registry-1.docker.io                                                                                                                                                                                       0.0s
 => [internal] load build context                                                                                                                                                                                                                      0.2s
 => => transferring context: 1.12kB                                                                                                                                                                                                                    0.0s
 => ERROR [1/3] FROM docker.io/abrarov/msvc-2019@sha256:5475e5e6b679b1ba68767788ab5e21fc56c4984fb8f2ad95a1d19ecb30e2bb27                                                                                                                             226.5s
 => => resolve docker.io/abrarov/msvc-2019@sha256:5475e5e6b679b1ba68767788ab5e21fc56c4984fb8f2ad95a1d19ecb30e2bb27                                                                                                                                     0.0s
 => => sha256:0a18a5cb7b3b29cdcea2057ba890751182c9a6b2d796149dbad3ae8597d41a0d 7.68kB / 7.68kB                                                                                                                                                         0.0s
 => => sha256:b111c3320c949bea81612bf4554f1b6592c2f504920b5bf57ba340a1d4d52c93 1.88GB / 1.88GB                                                                                                                                                       144.7s
 => => sha256:5475e5e6b679b1ba68767788ab5e21fc56c4984fb8f2ad95a1d19ecb30e2bb27 3.61kB / 3.61kB                                                                                                                                                         0.0s
 => => sha256:294d77ac553d7210b662d07674ef9e39a6c2e88dc15b9d2788d51e509bc8b54e 800.55MB / 800.55MB                                                                                                                                                    94.6s
 => => sha256:ca73064362226b7df47e746a33e9d3f10628ad09224721ff795618c85e2ff104 1.29kB / 1.29kB                                                                                                                                                         0.5s
 => => sha256:52e8bf960487dc434a52fd2c35af27d90be2a68350e23f11e4e3e8efe5f1e74a 3.81kB / 3.81kB                                                                                                                                                         0.9s
 => => sha256:d0423104b1e8eb4ba8f6f8b92f29f150f61c99e3ae0155329524ac2b435ae82f 1.26GB / 1.26GB                                                                                                                                                        37.2s
 => => sha256:e955cb691f75ed421e352c2b78022deb5a85b9b9ecf344a3f8ed9e3da1f896aa 1.29kB / 1.29kB                                                                                                                                                        38.1s
 => => sha256:12ba4d046135d63a754b968f6937a1fd6222c1da6862395b9e85e3e2174c2af5 1.29kB / 1.29kB                                                                                                                                                        38.5s
 => => sha256:ab9c362daf8c54ee2d2df390e3fdba4380942f37abe0c599fd5816a565af61b1 1.29kB / 1.29kB                                                                                                                                                        38.9s
 => => sha256:97fe756aa378d9353d0de56dcd51307ef6f1c14f529b722289c2aefc5e6721d6 1.32kB / 1.32kB                                                                                                                                                        39.2s
 => => sha256:79d7cc2a012d4048702581c5bf2773d36d1447eecc56955fe08dd5752b1208e1 2.47kB / 2.47kB                                                                                                                                                        40.2s
 => => sha256:33938a6a16796a5374e0d433c6d64afa545d3aa0e9728b5a86578bc29a174f76 2.80GB / 2.80GB                                                                                                                                                       103.2s
 => => sha256:4b1f05d62224ff3b95f806182ae0f7f694c46fd86bd088ed507a24f07b82d98b 1.29kB / 1.29kB                                                                                                                                                        96.4s
 => => sha256:db16aae2780dbcef1e8a024e2305c266a6840b07bc2714401c992420ed373b6b 1.30kB / 1.30kB                                                                                                                                                        96.7s
 => => sha256:b7578dffce361f42b3a3294c4efd9b906cb4330478ccb1c704e025ddba029eee 1.29kB / 1.29kB                                                                                                                                                        97.1s
 => => extracting sha256:b111c3320c949bea81612bf4554f1b6592c2f504920b5bf57ba340a1d4d52c93                                                                                                                                                             59.9s
 => => extracting sha256:294d77ac553d7210b662d07674ef9e39a6c2e88dc15b9d2788d51e509bc8b54e                                                                                                                                                             21.0s
------
 > [1/3] FROM docker.io/abrarov/msvc-2019@sha256:5475e5e6b679b1ba68767788ab5e21fc56c4984fb8f2ad95a1d19ecb30e2bb27:
------
failed to register layer: Error processing tar file(exit status 1): link /Files/Program Files/common files/Microsoft Shared/Ink/en-US/micaut.dll.mui /Files/Program Files (x86)/common files/Microsoft Shared/ink/en-US/micaut.dll.mui: no such file or directory
Copy Aseprite from Docker container
Unable to find image 'eddex/aseprite:latest' locally
docker: Error response from daemon: manifest for eddex/aseprite:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
Error response from daemon: No such container: aseprite
Error: No such container:path: aseprite:aseprite\build\bin
Error: No such container: aseprite
Done
```

I will try to figure out how to fix it.

**Comment by eddex** [comment] 2023-10-23 18:27
The error appears if you try to run the script with Linux containers enabled instead of Windows containers.

Right click on the Docker tray icon and check if it says "Switch to Linux containers...". If it says "Switch to Windows containers..." instead, click it to switch to Windows containers.$

This is what it looks like when you are using Windows containers:
![image](https://github.com/eddex/aseprite-windows-docker-build/assets/5302085/7dc9dae7-e9df-4a48-9696-71ea8fda48aa)

**Comment by leomarques** [comment] 2023-10-23 22:32
Hi @eddex, thanks a lot for the answer.
When I switch to Windows containers docker restarts and just stays forever on "starting the docker engine", I've let it running here for about 30 minutes now and no change.
Do you have any tips for that?

**Comment by leomarques** [comment] 2023-10-23 23:12
It worked, thanks a lot man, you're awesome.

**Comment by eddex** [comment] 2023-10-24 06:22
No problem 👍  I'll close this issue now.

**Closed by eddex** 2023-10-24 06:22 UTC
