### ISSUE TITLE
Cannot Produce Container ID

### ISSUE THREAD

**Issue by KingGamingYT** [eddex/aseprite-windows-docker-build#7] opened 2023-03-20 04:05 UTC
![image](https://user-images.githubusercontent.com/45918062/226243964-1b2b2edf-3d99-4bd8-96a1-a84db587d772.png)

**Comment by eddex** [comment] 2023-03-20 08:27
Hi :)

Try running `docker images` to see if the image has been built.
And make sure you have run the `docker build -t eddex/aseprite .` command before this. It takes several minutes to complete. Make sure you don't forget the `.` at the end of the command.

Hope this helps!

**Comment by KingGamingYT** [comment] 2023-03-20 19:54
> Hi :)
> 
> Try running `docker images` to see if the image has been built. And make sure you have run the `docker build -t eddex/aseprite .` command before this. It takes several minutes to complete. Make sure you don't forget the `.` at the end of the command.
> 
> Hope this helps!

Hi! There's something called "<none>", but I don't see anything related to eddex/aseprite
![image](https://user-images.githubusercontent.com/45918062/226446928-bf5720a3-af05-4fcc-9c9f-47a5223ca654.png)

Secondly, I noticed how two commands in build.bat fail in succession, cmake, and ninja. Ninja can't find a filling that I'm guessing is created by the cmake command, and cmake can't find a compiler.
![image](https://user-images.githubusercontent.com/45918062/226451092-88b760f5-b023-401c-972f-ebfef8f48cd6.png)

**Comment by eddex** [comment] 2023-03-20 20:58
Not sure why it doesn't work.. I just used the script 2 days ago and it was working fine. Are you using the latest version of the script?

**Comment by eddex** [comment] 2023-03-21 06:52
Well if you can run `build.bat` on your own machine (without the Docker commands), that's fine too.

Are you using Windows Containers? If not, that might be the issue here.
You can check this by right clicking the Docker tray icon. If it says "Switch to Linux containers..." then you are fine, if it says "Switch to Windows containers..." (like in the screenshot), then you have to click that option.
![image](https://user-images.githubusercontent.com/5302085/226536165-adc30056-01fc-4f45-b545-21e6e8b074d2.png)

With Docker, everything you need to build Aseprite is installed in a container that can then be deleted easily. The reason why I like this approach is because I don't have to install all the C++ stuff on my computer, since I don't work with C++ otherwise.

**Comment by KingGamingYT** [comment] 2023-03-21 12:02
I had to run `build.bat` manually because the docker script would sit on step 3 (executing build.bat) until it timed itself out.

**Comment by KingGamingYT** [comment] 2023-03-21 12:14
I'm currently away from my desktop at the moment, but I'll post the corresponding error message here when I get the chance.

**Comment by eddex** [comment] 2023-07-31 13:17
Closing this because I can't reproduce it and there hasn't been an update in a long time. Should this still be a problem, please re-open this issue.

**Closed by eddex** 2023-07-31 13:17 UTC
